# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:

#================================================================
# grpc
  proto:
    cmds:
      - echo "Creating gen/v1 directory..."
      - mkdir -p gen/v1
      - echo "Generating proto files..."
      - protoc --go_out=paths=source_relative:gen --go-grpc_out=paths=source_relative:gen --proto_path=proto proto/v1/**/*.proto
    silent: true

#================================================================
# build ssl certificates
  ssl:
    cmds:
      - cd ssl && ./instructions.sh
      
#==============================================================
# swagger
  swagger:
    cmds:
      - echo "swagger generating docs"
      - swag init -g **/**/*.go
    silent: true

  deps:
    cmds:
      - echo "Installing dependencies..."
      - go install github.com/swaggo/swag/cmd/swag@latest
      - go mod tidy
    silent: true