# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  PROTOS_PATH: ../nats_starter_protos/proto/v1

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  
  proto:
    cmds:
      - protoc --go_out=paths=source_relative:gen/v1 --go-grpc_out=paths=source_relative:gen/v1 --proto_path={{.PROTOS_PATH}} {{.PROTOS_PATH}}/authpb/*.proto