// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package postgres

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	UserID                 uuid.UUID      `json:"user_id"`
	Email                  string         `json:"email"`
	Username               string         `json:"username"`
	PasswordHash           []byte         `json:"password_hash"`
	VerificationCode       sql.NullString `json:"verification_code"`
	VerificationExpiration sql.NullTime   `json:"verification_expiration"`
	Verified               bool           `json:"verified"`
	Active                 bool           `json:"active"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
}
