// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetUserByID(ctx context.Context, userID uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, upper interface{}) (User, error)
	//------- USERS SAVE ------------------
	SaveUser(ctx context.Context, arg SaveUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
